// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeManager.Infrastructure.Persistence;

#nullable disable

namespace OvertimeManager.Infrastructure.Migrations
{
    [DbContext(typeof(OvertimeManagerDbContext))]
    partial class OvertimeManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeManager.Domain.Entities.Overtime.OvertimeCompensationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CompensatedTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CreatedForDay")
                        .HasColumnType("date");

                    b.Property<double>("Multiplier")
                        .HasColumnType("float");

                    b.Property<int>("RequesedForEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedForEmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("RequestedTime")
                        .HasColumnType("float");

                    b.Property<int>("RequesterdByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("RequestedForEmployeeId");

                    b.ToTable("OvertimeCompensationRequests");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.Overtime.OvertimeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualTime")
                        .HasColumnType("float");

                    b.Property<int>("ApprovalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessJustificationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CreatedForDay")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequesedForEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedForEmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("RequestedTime")
                        .HasColumnType("float");

                    b.Property<int>("RequesterdByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("RequestedForEmployeeId");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.Overtime.OvertimeRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OvertimeRequestsStatusses");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.User.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeSummaryId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OvertimeSummaryId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.User.EmployeeOvertimeSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("SettledOvertimet")
                        .HasColumnType("float");

                    b.Property<double>("TakenOvertime")
                        .HasColumnType("float");

                    b.Property<double>("UnsetledOvertime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OvertimeSummaries");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.User.EmployeeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.Overtime.OvertimeCompensationRequest", b =>
                {
                    b.HasOne("OvertimeManager.Domain.Entities.User.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId");

                    b.HasOne("OvertimeManager.Domain.Entities.User.Employee", "RequestedForEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedForEmployeeId");

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("RequestedForEmployee");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.Overtime.OvertimeRequest", b =>
                {
                    b.HasOne("OvertimeManager.Domain.Entities.User.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId");

                    b.HasOne("OvertimeManager.Domain.Entities.User.Employee", "RequestedForEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedForEmployeeId");

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("RequestedForEmployee");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.User.Employee", b =>
                {
                    b.HasOne("OvertimeManager.Domain.Entities.User.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OvertimeManager.Domain.Entities.User.EmployeeOvertimeSummary", "OvertimeSummary")
                        .WithMany()
                        .HasForeignKey("OvertimeSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeManager.Domain.Entities.User.EmployeeRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("OvertimeSummary");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OvertimeManager.Domain.Entities.User.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
